### ISSUE TITLE
Missing documents (jyu theses)

### ISSUE THREAD

**Issue by nwagner84** [NatLibFi/Annif-corpora#1]
I can't build the jyu theses corpus, because two documents are missing:

- [fulltext/jyu-theses/fin/2011-D-37180.url](https://github.com/NatLibFi/Annif-corpora/blob/master/fulltext/jyu-theses/fin/2011-D-37180.url)
- [fulltext/jyu-theses/fin/2017-M-54486.url](https://github.com/NatLibFi/Annif-corpora/blob/master/fulltext/jyu-theses/fin/2017-M-54486.url)

I changed the Makefile to proceed with this step. Now, if a download fails, the source (.url) and destination (.pdf) file is deleted.

```diff
%.pdf: %.url
-   wget -q --no-use-server-timestamps -O $@ -i $< || rm -f $@
+   wget -q --tries=5 --no-use-server-timestamps -O $@ -i $< || rm -f $@ $<
```

Also, if the conversion from text to pdf fails the complete process stops. I fixed this with the following change (all conversion errors are ignored):

```diff
%.txt: %.pdf
-   pdftotext $<
+   pdftotext $< || true
```

Finally, it may be worth to mention in the documentation, that it is possible to speed up the process of downloading and converting with `make -j16 pdf` or `make -j4 txt`.

**Comment by osma** [comment]
Thanks, good points.

With a large repository like JYX, changes will happen to individual documents - some may get moved around, deleted etc. When the Makefile was written, those URLs still worked fine.

Would you like to make a pull request with the suggested changes?

**Comment by nwagner84** [comment]
@osma see the linked pull request.
